memberaccount/urls.py
from django.urls import path
from memberaccount import views

app_name = 'memberaccountnewuser'
urlpatterns = [
    path('signup/', views.signUp, name='signup'),
    path('signin/', views.signIn, name='signin'),
]

thefinalrealversionfoodmapNewversion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from thenavbarandhomepage import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('', include('memberaccount.urls')),
    path('', include('thenewmapandchart.urls')),
    path('', include('thenewsetupmapandchart.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thenewsetupmapandchart/urls.py
from django.urls import path
from thenewsetupmapandchart import views
app_name = 'chartandmap'
urlpatterns = [
    path('charts/', views.charts, name="charts"),
    path('map/', views.maps, name="map"),
    path('chartsormapdetails/<int:pk>', views.chartsandmapdetail, name="detail"),
    path('menu/<int:pk>', views.menu, name="menu"),
    path('reviewdisplay/<int:pk>', views.reviewdisplay, name="reviewdisplay"),
    path('meals/<int:pk>', views.meals, name="meals"),
]

thenewsetupmapandchart/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.


class newsetupFoodmapStore(models.Model):

    ratingcategories_choice = {
        ('4.5分或以上', '4.5分或以上'),
        ('4分或以上', '4分或以上'),
        ('3分或以上', '3分或以上'),
    }

    district_choice = {
        ('淡大校內', '淡大校內'),
        ('大學城', '大學城'),
        ('水源街', '水源街'),
        ('大田寮', '大田寮'),
        ('金雞母', '金雞母'),
    }

    restauranttype_choice = {
        ('健康餐廳', '健康餐廳'),
        ('台式料理店', '台式料理店'),
        ('早午餐店', '早午餐店'),
        ('滷味店', '滷味店'),
        ('義式料理餐廳', '義式料理餐廳'),
        ('炸物店', '炸物店'),
        ('美式料理餐廳', '美式料理餐廳'),
        ('麵食館', '麵食館'),
        ('便當店', '便當店'),
        ('中式料理餐廳', '中式料理餐廳'),
        ('日式料理餐廳', '日式料理餐廳'),
        ('吃到飽餐廳', '吃到飽餐廳'),
        ('串燒烤肉店', '串燒烤肉店'),
        ('冰品飲料店', '冰品飲料店'),
        ('火鍋餐廳', '火鍋餐廳'),
        ('韓式料理餐廳', '韓式料理餐廳'),
        ('素食餐廳', '素食餐廳'),
        ('咖啡廳', '咖啡廳'),
        ('甜品店', '甜品店'),
        ('輕食餐廳', '輕食餐廳'),
        ('自助餐店', '自助餐店'),
        ('排餐餐廳', '排餐餐廳'),
        ('港式料理餐廳', '港式料理餐廳'),
    }




    district = models.CharField(max_length=30, blank=True, null=True, choices=district_choice)
    restaurantname = models.CharField(max_length=250)
    address = models.TextField()
    contactinfo = models.TextField()
    googlereviewlink = models.TextField()
    # restaurantcoverphoto = models.ImageField(max_length=100, default=0, upload_to='staticFiles/img')
    restaurantcoverphotourl = models.URLField(max_length=300, default='')
    googlemapiframeembeddedcode = models.TextField()
    openingtime = models.TextField()
    latitude = models.FloatField(null=False)
    longitude = models.FloatField(null=False)
    ratingintotaloffive = models.FloatField()
    ratingcategories = models.CharField(max_length=30, blank=True, null=True, choices=ratingcategories_choice)
    restauranttype = models.CharField(max_length=30, blank=True, null=True, choices=restauranttype_choice)
    totalreviewnumber = models.CharField(max_length=300, blank=False, null=False,)
    commentOne = models.TextField()
    commentTwo = models.TextField()
    commentThree = models.TextField()
    commentFour = models.TextField()
    commentFive = models.TextField()
    foodmapmenuOne = models.URLField(max_length=300, default='')
    foodmapmenuTwo = models.URLField(max_length=300, default='')
    foodmapmenuThree = models.URLField(max_length=300, default='')
    foodmapmenuFour = models.URLField(max_length=300, default='')
    foodmapmenuFive = models.URLField(max_length=300, default='')
    foodmapmenuSix = models.URLField(max_length=300, default='')
    foodmapmenuSeven = models.URLField(max_length=300, default='')
    foodmapmenuEight = models.URLField(max_length=300, default='')
    foodmapmenuNine = models.URLField(max_length=300, default='')
    foodmapDishesOne = models.URLField(max_length=300, default='')
    foodmapDishesTwo = models.URLField(max_length=300, default='')
    foodmapDishesThree = models.URLField(max_length=300, default='')
    # extractedpngfilename = models.CharField(max_length=200, default='', blank=True, null=True)

    def __str__(self):
        return self.restaurantname

thenewsetupmapandchart/views.py
from django.shortcuts import render
from .models import newsetupFoodmapStore


# Create your views here.


def charts(request):
    foodstoresinfochart = newsetupFoodmapStore.objects.all();
    return render(request, 'charts.html', {'foodstoresinfochart': foodstoresinfochart})


def maps(request):
    foodstores = list(
        newsetupFoodmapStore.objects.values('id', 'district', 'restaurantname', 'address', 'contactinfo',
                                            'googlereviewlink', 'openingtime', 'latitude', 'longitude',
                                            'ratingintotaloffive', 'ratingcategories', 'restauranttype',
                                            'restaurantcoverphotourl')[:85])

    # 'district', 'restaurantname', 'address', 'contactinfo', 'googlereviewlink',
    # 'openingtime',
    # 'latitude', 'longitude', 'ratingintotaloffive', 'ratingcategories',
    # 'restauranttype', 'restaurantcoverphoto', 'restaurantcoverphotourl')[:85])
    foodstoresinfo = newsetupFoodmapStore.objects.all();

    context = {'foodstores': foodstores,
               'foodstoresinfo': foodstoresinfo, }

    return render(request, 'map.html', context)


def chartsandmapdetail(request, pk):
    foodstoresinfodetail = newsetupFoodmapStore.objects.get(id=pk);
    return render(request, 'chartsandmapdetail.html', {'foodstoresinfodetail': foodstoresinfodetail})


def menu(request,pk):
    foodstoresmenu = newsetupFoodmapStore.objects.get(id=pk);
    return render(request, 'menu.html', {'foodstoresmenu': foodstoresmenu})


def reviewdisplay(request,pk):
    foodstoresreview = newsetupFoodmapStore.objects.get(id=pk);
    return render(request, 'review.html', {'foodstoresreview': foodstoresreview})


def meals(request,pk):
    foodstoresmeals = newsetupFoodmapStore.objects.get(id=pk);
    return render(request, 'meals.html', {'foodstoresmeals': foodstoresmeals})

thenewsetupmapandchart/templates/charts.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}
    <div class="ChartsList">
        <div class="top">
            <img src="{% static 'img/3F3F3F29 1.png' %}" alt="">排行榜
        </div>
    </div>
    <ul class="list-group">
        {% for list in foodstoresinfochart %}
        <a class="groupref" href="{% url 'chartandmap:detail' list.id %}">
        <li class="list-group-item">
            <div>
                <div class="content">
                    <div>
                        <h1 class="font-weight-bold mb-1">{{ list.restaurantname }}</h1>
                        <p class="font-weight-bold mb-1">地址：{{ list.address }}
                        </p>
                        <p class="font-weight-bold mb-1">餐廳種類：{{ list.restauranttype }}</p>
                        <img src="{{ list.restaurantcoverphotourl}}" alt="foodpic" width="150">
                    </div>
                    <div class="ratingintotaloffive" style="position: absolute; right:100px;">
                    <div class="rounded-circle">
                        <h6>{{ list.ratingintotaloffive }}</h6>
                    </div>
                    </div>
                </div><!--<img src="staticFiles/img/下載 1.png" alt="foodpic" width="150">-->
            </div>
        </li>
        </a>
        {% endfor %}

        <!--<li class="list-group-item">
            <div>
                <div class="content">
                    <div>
                        <h1 class="font-weight-bold mb-1">八方雲集 (淡水學府店)</h1>
                        <p class="font-weight-bold mb-1">地點：251新北市淡水區學府路104號
                        </p>
                        <p class="font-weight-bold mb-1">種類：臺式料理</p>
                    </div>
                    <div class="rounded-circle">
                        <h6>4.5</h6>
                    </div>
                </div><img src="media/下載 1.png" alt="foodpic" width="150">
            </div>
        </li>

        <li class="list-group-item">
            <div>
                <div class="content">
                    <div>
                        <h1 class="font-weight-bold mb-1">八方雲集 (淡水學府店)</h1>
                        <p class="font-weight-bold mb-1">地點：251新北市淡水區學府路104號
                        </p>
                        <p class="font-weight-bold mb-1">種類：臺式料理</p>
                    </div>
                    <div class="rounded-circle">
                        <h6>4.5</h6>
                    </div>
                </div><img src="media/下載 1.png" alt="foodpic" width="150">
            </div>
        </li>

        <li class="list-group-item">
            <div>
                <div class="content">
                    <div>
                        <h1 class="font-weight-bold mb-1">八方雲集 (淡水學府店)</h1>
                        <p class="font-weight-bold mb-1">地點：251新北市淡水區學府路104號
                        </p>
                        <p class="font-weight-bold mb-1">種類：臺式料理</p>
                    </div>
                    <div class="rounded-circle">
                        <h6>4.5</h6>
                    </div>
                </div><img src="media/下載 1.png" alt="foodpic" width="150">
            </div>
        </li> -->


    </ul>
{% endblock %}

thenewsetupmapandchart/templates/chartsandmapdetail.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}
    {% if foodstoresinfodetail %}
    <div class="content m-3" style="display: flex; justify-items: center; align-items: center;">
        <img src="{{foodstoresinfodetail.restaurantcoverphotourl}}" alt="" width="200">
        <div class="m-2">
    {% endif %}
            <p style="font-size: 14px; margin: 0; color: #48C97C;">{{ foodstoresinfodetail.restaurantname }}</p>
            <p style="font-size: 14px; margin: 0; color: #64E2F4;">餐廳種類：{{ foodstoresinfodetail.restauranttype }}</p>
            <p style="font-size: 14px; margin: 0; color: #64E2F4;">地址：{{ foodstoresinfodetail.address }}</p>
            <p style="font-size: 14px; margin: 0; color: #BDC977;">聯絡資訊：{{ foodstoresinfodetail.contactinfo }}</p>
            <p style="font-size: 14px; margin: 0; color: #FF22E9;">評分：4.8</p>
            <p style="font-size: 14px; margin: 0; color: #FFFFFF;">營業時間：{{ foodstoresinfodetail.openingtime }}</p>
            <div class="district-detail" style="position: absolute; left:30px; transform: translate(0, 50px);">
            <!--<div class="district-detail"></div>-->
            <p style="font-size: 14px; margin:0; color: #4BC97C;">區域：{{ foodstoresinfodetail.district }}</p>
            </div>
        </div>
    </div>

    <div class="content2 justify-content-end" style="display: flex; justify-items: center; align-items: center;">

        {% autoescape off %}
        {{foodstoresinfodetail.googlemapiframeembeddedcode}}
        {% endautoescape %}

        <!--<iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3610.8639712085283!2d121.44472051144521!3d25.174070577632943!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442aff8c1544bdb%3A0x1dcf4f494b3362b!2z5reh5rGf5aSn5a24!5e0!3m2!1szh-TW!2stw!4v1693565141787!5m2!1szh-TW!2stw"
            width="30%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
        </iframe>-->

        <div class="google_conment">
            <div style="display: flex;">

                <p class="m-3" style="background-color: #fff;">
                    <a href="{{ foodstoresinfodetail.googlereviewlink }}" style="text-decoration:none;  color: black;;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                            class="bi bi-google" viewBox="0 0 16 16">
                            <path
                                d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z">
                            </path>
                        </svg>評論:{{ foodstoresinfodetail.totalreviewnumber }}
                    </a>
                </p>

            </div>
        </div>
    </div>

    <!--<div class="store_comment_and_pic m-3">
        <p style="color: #fff;">評論/店家圖片：</p>
    </div>-->

    <!-- Container for absolute positioning -->
    <div class="container-chartsormapdetail">
        <!-- Absolute centered rectangle block -->
        <div class="rectangle-block">
            <a href="{% url 'chartandmap:menu' foodstoresinfodetail.id %}" class="image-button" style="left: 15%;">
                <img src="{% static 'img/Component1.png' %}" alt="Button 1" style="max-width: 300px; max-height: 200px;">
            </a>
            <a href="{% url 'chartandmap:reviewdisplay' foodstoresinfodetail.id %}" class="image-button" style="left: 50%;">
                <img src="{% static 'img/Component2.png' %}" alt="Button 2" style="max-width: 300px; max-height: 200px;">
            </a>
            <a href="{% url 'chartandmap:meals' foodstoresinfodetail.id %}" class="image-button" style="left: 85%;">
                <img src="{% static 'img/Component3.png' %}" alt="Button 3" style="max-width: 300px; max-height: 200px;">
            </a>
        </div>
    </div>

{% endblock %}

thenewsetupmapandchart/templates/meals.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}



    {% if foodstoresmeals.foodmapDishesOne %}
   <!-- <div class="carousel-item active">-->
      <img src="{{foodstoresmeals.foodmapDishesOne}}" class="d-block w-100" alt="..." style="max-width: 45%">
    </div>
     {% endif %}

    {% if foodstoresmeals.foodmapDishesTwo %}
    <!--<div class="carousel-item active">-->
      <img src="{{ foodstoresmeals.foodmapDishesTwo }}" class="d-block w-100" alt="..." style="max-width: 45%">
    </div>
    {% endif %}

    {% if foodstoresmeals.foodmapDishesThree %}
    <!--<div class="carousel-item active">-->
      <img src="{{ foodstoresmeals.foodmapDishesThree }}" class="d-block w-100" alt="..." style="max-width: 45%">
    </div>
    {% endif %}



  <!--<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>-->

<!--    <div id="myCarousel" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>




{% endblock %}

thenewsetupmapandchart/templates/menu.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}


<!--<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="6" aria-label="Slide 7"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="7" aria-label="Slide 8"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="8" aria-label="Slide 9"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="9" aria-label="Slide 10"></button>
  </div>-->

  <!--<div class="carousel-inner">-->

    {% if foodstoresmenu.foodmapmenuOne %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuOne }}" class="d-block w-100" alt="...">
    </div>
     {% endif %}

    {% if foodstoresmenu.foodmapmenuTwo %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuTwo }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuThree %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuThree }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuFour %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuFour }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuFive %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuFive }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuSix %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuSix }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuSeven %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuSeven }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

     {% if foodstoresmenu.foodmapmenuEight %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuEight }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}

    {% if foodstoresmenu.foodmapmenuNine %}
    <div class="carousel-item active">
      <img src="{{ foodstoresmenu.foodmapmenuNine }}" class="d-block w-100" alt="...">
    </div>
    {% endif %}
  </div>


 <!-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button> -->
</div>


{% endblock %}

thenewsetupmapandchart/templates/review.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}

<div class="reviewOne" style="color:#FFFFFF;">
{% if foodstoresreview.commentOne %}
    <p>{{ foodstoresreview.commentOne }}</p>
{% endif %}
</div>

<div class="reviewTwo" style="color: #FFFFFF;">
{% if foodstoresreview.commentTwo %}
    <p>{{ foodstoresreview.commentTwo }}</p>
{% endif %}
</div>

<div class="reviewThree" style="color: #FFFFFF">
{% if foodstoresreview.commentThree %}
    <p>{{ foodstoresreview.commentThree }}</p>
{% endif %}
</div>

<div class="reviewFour" style="color:#FFFFFF">
{% if foodstoresreview.commentFour %}
    <p>{{ foodstoresreview.commentFour }}</p>
{% endif %}
</div>

<div class="reviewFive" style="color:#FFFFFF">
{% if foodstoresreview.commentFive %}
    <p>{{ foodstoresreview.commentFive }}</p>
{% endif %}
</div>

{% endblock %}