memberaccount/urls.py
from django.urls import path
from memberaccount import views

app_name = 'memberaccountnewuser'
urlpatterns = [
    path('signup/', views.signUp, name='signup'),
    path('signin/', views.signIn, name='signin'),
]

thefinalrealversionfoodmapNewversion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from thenavbarandhomepage import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('', include('memberaccount.urls')),
    path('', include('thenewmapandchart.urls')),
    path('', include('thenewsetupmapandchart.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

thenewsetupmapandchart/urls.py
from django.urls import path
from thenewsetupmapandchart import views
app_name = 'chartandmap'
urlpatterns = [
    path('charts/', views.charts, name="charts"),
    path('map/', views.maps, name="map"),
    path('chartsormapdetails/<int:pk>', views.chartsandmapdetail, name="detail"),
    path('menu/<int:pk>', views.menu, name="menu"),
    path('reviewdisplay/<int:pk>', views.reviewdisplay, name="reviewdisplay"),
    path('meals/<int:pk>', views.meals, name="meals"),
]

templates/aboutUs.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
{% load static %}
<div style="display: flex; align-items: center; justify-content: center;">
    <h3 class="m-3" style="color: #85B6FF;">關於我們-淡江好食光</h3>
</div>

<div class="m-3" style="display: flex; align-items: center; justify-content: center; font-size: 35px; ">
    <h4 style="color: #fff;">
        想知道淡江大學有什麼美食嗎？<br> <br>

淡江好食光收錄了淡大校內的店家，以及附近區域：「大學城、大田寮、金雞母、水源街」的美食店家。
<br>
<br>
等你來探索喔！快來看看吧～
    </h4>
</div>

<div class="cartoon_map m-3" style="display: flex; align-items: center; justify-content: center;">
    <img style="width: 100%;" src="{% static 'img/S__3862200411.png' %}" alt="">
</div>

{% endblock %}

templates/homepage.html
{% extends 'thenavbarandbackground.html' %}
{% block content %}
<div class="banner">
        <!-- <img src="/media/淡江大學城 1.png" alt=""> -->
        <!-- <h3 style="text-align: center;">adwdawds<br>dsadwdawdaw</h3> -->

        {% load static %}
        <img src="{% static 'img/淡江大學城 1.png'%}" alt="">
        <div class="title">
            <h1>想不到吃什麼嗎？<br>來用好食光，美食吃光光</h1>
            <button class="map"><a href="{% url 'chartandmap:map' %}"><img src="{% static 'img/tomapimage.png'%}" alt="">前往地圖</a></button>
        </div>
    </div>

    <div class="contain1">
        <img src="{% static 'img/淡江大學城2 1.png'%}" alt="">
        <p>本網站蒐集了淡江大學附近各個區域的店家資料，以及做了詳細統整，讓同學們可以更清楚了解自己所屬的區域有哪些店家在經營。</p>

    </div>

    <div class="contain2">
        <p>在眾多店家中，本網站根據最具權威的來源資料中作了由高至低的排名，同學們可根據排行榜的高低來判斷店家是否可靠。</p>
        <img src="{% static 'img/大學城3 1.png'%}" alt="">
    </div>

    <button class="charts"><a href="{% url 'chartandmap:charts' %}"><img src="{% static 'img/3F3F3F29 1.png'%}" alt="">前往排行榜</a></button>

{% endblock %}

templates/thenavbarandbackground.html
{% load static %}
{% load static from static %}
<!DOCTYPE html>
<html lang="zh-hant">

<head>
    <meta charset="utf-8">
    <!--響應式網站的功能導入程式-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HomePage</title>

    <!--Bootstrap5.3 導入程式-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>


    <!--leaflet導入程式-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>


    <!-- 連結CSS -->
    <!--<link rel="stylesheet" href="css/notOwnProfile_style.css">-->
    <!--<link rel="stylesheet" href="css/post_create_style.css">-->
    <!--<link rel="stylesheet" href="css/post_detail_style.css">-->
    <!--<link rel="stylesheet" href="css/post_list_style.css">-->
    <!--<link rel="stylesheet" href="css/signin_form_style.css">-->
    <link rel="stylesheet" href="{% static 'css/signup_form_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/chartsormapdetailpage.css' %}">
    <!--<link rel="stylesheet" href="css/UserProfileList.css">-->
    <link rel="stylesheet" href="{% static 'css/Charts.css' %}">
    <link rel="stylesheet" href="{% static 'css/Map.css' %}">

</head>

<body>
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <!--品牌Logo-->
            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{% static 'img/Logo.png' %}" style="height: 100px"></a>

            <!--第一部分：手機版-->
            <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- 第二𨚪分：桌上型電腦版 -->

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chartandmap:map' %}">地圖</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chartandmap:charts' %}">排行榜</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chartandmap:charts' %}">關於我們</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chartandmap:charts' %}">會員新增店家</a>
                    </li>


                    <!--<li class="nav-item">
                        <a class="nav-link" href="#">追蹤創作者</a>
                    </li>-->

                    <!--<li class="nav-item">
                        <a class="nav-link" href="% url 'profile:nonsignupsigninprofilelist' %">關注創作者</a>
                    </li>-->

                    <li class="nav-item-enter">
                        <a class="nav-link" href="{% url 'memberaccountnewuser:signup' %}">
                            <button type="submit">註冊/登入</button>
                        </a>
                    </li>

                    <!--<li class="nav-item-enter">
                        <a class="nav-link" href="#">
                            <button type="submit">帖文創作</button>
                        </a>
                    </li>-->

                </ul>
            </div>
        </div>
    </nav>




    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>


</body>



</html>